# Generated by Django 5.2.5 on 2025-08-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("MATH", "Engineering Mathematics"),
                            ("DL", "Digital Logic"),
                            ("COA", "Computer Organization and Architecture"),
                            ("PROG", "Programming and Data Structures"),
                            ("ALGO", "Algorithms"),
                            ("TOC", "Theory of Computation"),
                            ("CD", "Compiler Design"),
                            ("OS", "Operating Systems"),
                            ("DB", "Database Management Systems"),
                            ("CN", "Computer Networks"),
                            ("GA", "General Aptitude"),
                        ],
                        max_length=4,
                    ),
                ),
                ("topic", models.CharField(max_length=100)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("EASY", "Easy"),
                            ("MEDIUM", "Medium"),
                            ("HARD", "Hard"),
                        ],
                        default="MEDIUM",
                        max_length=6,
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("MCQ", "Multiple Choice Question"),
                            ("MSQ", "Multiple Select Question"),
                            ("NAT", "Numerical Answer Type"),
                        ],
                        default="MCQ",
                        max_length=4,
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.CharField(max_length=200)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("marks", models.IntegerField(default=1)),
            ],
        ),
    ]
