# Generated by Django 5.2.5 on 2025-08-08 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_question"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("MATH", "Engineering Mathematics"),
                            ("DL", "Digital Logic"),
                            ("COA", "Computer Organization and Architecture"),
                            ("PROG", "Programming and Data Structures"),
                            ("ALGO", "Algorithms"),
                            ("TOC", "Theory of Computation"),
                            ("CD", "Compiler Design"),
                            ("OS", "Operating Systems"),
                            ("DB", "Database Management Systems"),
                            ("CN", "Computer Networks"),
                            ("GA", "General Aptitude"),
                        ],
                        max_length=4,
                    ),
                ),
                ("score", models.IntegerField()),
                ("total_marks", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
