# Generated by Django 5.2.5 on 2025-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_quizresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("publication_date", models.DateTimeField()),
                ("source", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["-publication_date"],
            },
        ),
    ]
