# Generated by Django 5.2.5 on 2025-08-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_newsarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="explanation_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="explanation_images/"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="option_a_image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_b_image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_c_image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="option_d_image",
            field=models.ImageField(blank=True, null=True, upload_to="option_images/"),
        ),
        migrations.AddField(
            model_name="question",
            name="question_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="question_images/"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_paper",
            field=models.CharField(
                blank=True,
                help_text="e.g., GATE 2024 Session 1",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
