# Generated by Django 5.2.5 on 2025-08-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_challenge_challengeattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="source_paper_tag",
        ),
        migrations.AddField(
            model_name="challenge",
            name="config",
            field=models.JSONField(
                default=dict,
                help_text='Define the number of questions per subject. E.g., {"GA": 10, "ALGO": 8}',
            ),
        ),
    ]
